version: '2.1'
services:
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - 6379
    volumes:
      - 'redis:/var/lib/redis/data'
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
    redis:
    postgres:
