terms:
  - term: "School of the Arts"
  - term: "College of the Arts, Humanities and Social Sciences"
  - term: "College of Education, Kinesiology & Social Work"
  - term: "College of Science"
  - term: "College of Business Administration"
