terms:
  - term: "School of Engineering"
  - term: "School of Letters and Sciences"
  - term: "School of Maritime Trransportation, Logistics & Managemenet"
  - term: "Academic Senate"
  - term: "Cal Maritime Library"
  - term: "Administration"
  - term: "Office of the President"
