terms:
  - term: "School of Arts and Humanities"
  - term: "School of Business and Public Administration"
  - term: "School of Natural Sciences, Mathematics, and Engineering"
  - term: "School of Social Sciences and Education"
