terms:
  - term: "Business Administration"
  - term: "Education & Integrative Studies"
  - term: "Engineering"
  - term: "Environmental Design"
  - term: "Letters, Arts, & Social Sciences"
  - term: "Science"
  - term: "Don B. Huntley College of Agriculture"
  - term: "Collins College of Hospitality Management"
