terms:
  - term: "Arts and Letters"
  - term: "Business Administration"
  - term: "Education"
  - term: "Engineering and Computer Science"
  - term: "Health and Human Services"
  - term: "Natural Sciences and Mathematics"
  - term: "Social Sciences and Interdisciplinary Studies"
