terms:
  - term: "Social Sciences"
  - term: "Science and Technology"
  - term: "Business and Economics"
  - term: "Education"
  - term: "Arts and Humanities"
  - term: "Extended Education & International Education"
