terms:
  - term: "College of Business and Economics"
  - term: "College of Education and Allied Studies"
  - term: "College of Letters, Arts and Social Sciences"
  - term: "School of Arts & Media"
  - term: "School of Global Humanities & Cultural Studies"
  - term: "College of Science"
