terms:
  - term: "Engineering"
  - term: "Letters and Science"
  - term: "Maritime Transportation, Logistics & Management"
  - term: "Academic Senate"
  - term: "Library"
  - term: "Administration"
  - term: "Office of the President"
