terms:
  - term: "Academic Affairs"
  - term: "Academic Senate"
  - term: "Administrative Services"
  - term: "Athletics"
  - term: "College of Arts and Humanities"
  - term: "College of Health and Human Services"
  - term: "College of Science and Mathematics"
  - term: "College of Social Sciences"
  - term: "Craig School of Business"
  - term: "Financial Services"
  - term: "Henry Madden Library"
  - term: "Jordan College of Agricultural Sciences and Technology"
  - term: "Kremen School of Education and Human Development"
  - term: "Lyles College of Engineering"
  - term: "Office of the President"
  - term: "Student Affairs and Enrollment Management"
  - term: "Technology Services"
