terms:
  - term: "Academic Affairs"
  - term: "Academic Senate"
  - term: "Administrative Services"
  - term: "Athletics"
  - term: "Arts and Humanities"
  - term: "Health and Human Services"
  - term: "Science and Mathematics"
  - term: "Social Sciences"
  - term: "Craig School of Business"
  - term: "Financial Services"
  - term: "Henry Madden Library"
  - term: "Jordan College of Agricultural Sciences and Technology"
  - term: "Kremen School of Education and Human Development"
  - term: "Lyles College of Engineering"
  - term: "Office of the President"
  - term: "Student Affairs and Enrollment Management"
  - term: "Technology Services"
