terms:
  - term: "School of Social Sciences"
  - term: "School of Science and Technology"
  - term: "School of Business and Economics"
  - term: "School of Education"
  - term: "School of Arts and Humanities"
  - term: "School of Extended Education & International Education"
