terms:
  - term: AUD
  - term: BA
  - term: BS
  - term: DNP
  - term: DPT
  - term: DPTSC
  - term: EdD
  - term: EdS
  - term: MA
  - term: MAGED
  - term: MARA
  - term: MARCH
  - term: MAT
  - term: MBA
  - term: MBT
  - term: MCP
  - term: MCRP
  - term: MENG
  - term: MFA
  - term: MIA
  - term: MKM
  - term: MLA
  - term: MLIS
  - term: MM
  - term: MPA
  - term: MPACC
  - term: MPH
  - term: MPP
  - term: MPPA
  - term: MPS
  - term: MPT
  - term: MS
  - term: MSW
  - term: MUP
  - term: MURP
  - term: PhD
  - term: Other
