terms:
  - term: "Academic Policies & Planning Committee"
  - term: "Academic Senate Meetings"
  - term: "Accountancy"
  - term: "Administrative Division"
  - term: "Advancement"
  - term: "Aerospace Studies"
  - term: "Africana Studies Program"
  - term: "Agricultural Business"
  - term: "Animal Sciences and Agricultural Education"
  - term: "Anthropology"
  - term: "Armenian Studies Program"
  - term: "Art and Design"
  - term: "Biology"
  - term: "Business Teacher Education"
  - term: "Chemistry"
  - term: "Chicano and Latin American Studies"
  - term: "Child, Family and Consumer Sciences"
  - term: "Civil and Geomatics Engineering"
  - term: "Communication"
  - term: "Communicative Disorders and Deaf Studies"
  - term: "Computer Science"
  - term: "Construction Management Program"
  - term: "Counselor Education and Rehabilitation"
  - term: "Criminology"
  - term: "Curriculum and Instruction"
  - term: "Digital Services Division"
  - term: "Doctoral Program in Educational Leadership"
  - term: "Earth and Environmental Sciences"
  - term: "Economics"
  - term: "Education"
  - term: "Educational Leadership"
  - term: "Electrical and Computer Engineering"
  - term: "English"
  - term: "Executive Committee"
  - term: "FACEL"
  - term: "Faculty Equity & Diversity"
  - term: "Finance and Business Law"
  - term: "Fine Arts"
  - term: "Food Science and Nutrition"
  - term: "Geography and City & Regional Planning"
  - term: "Graduate Committee"
  - term: "History"
  - term: "Humanities"
  - term: "Industrial Arts"
  - term: "Industrial Technology"
  - term: "Information Systems and Decision Sciences"
  - term: "Intellectual Property Review Committee"
  - term: "Kinesiology"
  - term: "Life Science"
  - term: "Linguistics"
  - term: "Literacy, Early, Bilingual, and Special Education"
  - term: "Management"
  - term: "Marketing and Logistics"
  - term: "Mass Communication and Journalism"
  - term: "Mathematics"
  - term: "Mechanical Engineering"
  - term: "Military Science (Army ROTC)"
  - term: "Modern and Classical Languages and Literatures"
  - term: "Music"
  - term: "Nominating / Elections Committee"
  - term: "Personnel Committee"
  - term: "Philosophy"
  - term: "Physical Education"
  - term: "Physical Therapy"
  - term: "Physics"
  - term: "Plant Science"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Public Health"
  - term: "Public Services Division"
  - term: "Recreation Administration"
  - term: "Research Awards Review Committee"
  - term: "School of Nursing"
  - term: "Social Science"
  - term: "Social Work Education"
  - term: "Sociology"
  - term: "Special Collections Research Centers Division"
  - term: "Speech Arts"
  - term: "Student Affairs"
  - term: "Theatre Arts"
  - term: "Viticulture and Enology"
  - term: "Women's Studies Program"
