terms:
  - term: "Mechanical Engineering"
  - term: "Engineering Technology"
  - term: "Culture and Communication"
  - term: "Global Studies and Maritime Affairs"
  - term: "Sciences and Mathematics"
  - term: "International Business and Logistics"
  - term: "Marine Transportation"
  - term: "Naval Science"
