terms:
  - term: "Anthropology"
  - term: "Art"
  - term: "Asian Studies"
  - term: "Biological Sciences"
  - term: "Business Administration"
  - term: "Chemistry"
  - term: "Child Development"
  - term: "Civil Engineering"
  - term: "Communication Sciences and Disorders"
  - term: "Communication Studies"
  - term: "Computer Engineering"
  - term: "Computer Science"
  - term: "Construction Management"
  - term: "Criminal Justice"
  - term: "Design"
  - term: "Economics"
  - term: "Electrical and Electronic Engineering"
  - term: "English"
  - term: "Environmental Studies"
  - term: "Ethnic Studies"
  - term: "Family and Consumer Sciences"
  - term: "Geography"
  - term: "Geology"
  - term: "Gerontology"
  - term: "Graduate and Professional Studies in Education"
  - term: "Government"
  - term: "History"
  - term: "Humanities and Religious Studies"
  - term: "Kinesiology and Health Science"
  - term: "Liberal Studies"
  - term: "Mathematics and Statistics"
  - term: "Mechanical Engineering"
  - term: "Music"
  - term: "Nursing"
  - term: "Philosophy"
  - term: "Physical Therapy"
  - term: "Physics and Astronomy"
  - term: "Psychology"
  - term: "Public Policy and Administration"
  - term: "Recreation, Parks and Tourism"
  - term: "Social Science"
  - term: "Social Work"
  - term: "Sociology"
  - term: "Special Major"
  - term: "Teaching Credentials"
  - term: "Theatre and Dance"
  - term: "Women's Studies"
  - term: "World Languages and Literatures"
