terms:
  - term: "Accounting & Finance"
  - term: "Anthropology, Geography & Environmental Studies"
  - term: "Art"
  - term: "Biological Sciences"
  - term: "Chemistry & Biochemistry"
  - term: "Communication"
  - term: "Computer Science"
  - term: "Criminal Justice"
  - term: "Earth & Environmental Sciences, Geology"
  - term: "Economics"
  - term: "Educational Leadership"
  - term: "Educational Psychology"
  - term: "Engineering"
  - term: "English"
  - term: "Ethnic Studies"
  - term: "History"
  - term: "Hospitality, Recreation and Tourism"
  - term: "Human Development & Women's Studies"
  - term: "Kinesiology"
  - term: "Management"
  - term: "Marketing"
  - term: "Mathematics"
  - term: "Modern Languages & Literatures"
  - term: "Music"
  - term: "Nursing & Health Sciences"
  - term: "Philosophy & Religious Studies"
  - term: "Physics"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Public Affairs & Administration"
  - term: "Sociology & Social Services"
  - term: "Speech, Language, and Hearing Sciences"
  - term: "Statistics and Biostatistics"
  - term: "Teacher Education"
  - term: "Theatre & Dance"
