terms:
  - term: "Agriculture"
  - term: "Anthropology"
  - term: "Art and Art History"
  - term: "Biological Sciences"
  - term: "Business Administration"
  - term: "Communication Studies"
  - term: "Computer Science"
  - term: "Education"
  - term: "Electrical and Computer Engineering"
  - term: "English"
  - term: "Environmental Science"
  - term: "Geography"
  - term: "Geological and Environmental Sciences"
  - term: "Geosciences"
  - term: "Honors"
  - term: "History"
  - term: "Instructional Technology"
  - term: "Interdisciplinary Studies"
  - term: "International Languages, Literatures, and Cultures"
  - term: "Kinesiology"
  - term: "Mathematics and Statistics"
  - term: "Music"
  - term: "Nursing"
  - term: "Nutrition and Food Science"
  - term: "Political Science and Criminal Justice"
  - term: "Psychology"
  - term: "Public Administration"
  - term: "Recreation, Hospitality, and Parks Management"
  - term: "Social Science"
  - term: "Social Work"
  - term: "Science Education"
