terms:
  - term: "University Extended Education"
  - term: "University Library"
  - term: "Department of Art"
  - term: "Department of Music"
  - term: "Department of Theatre"
  - term: "Department of Anthropology, Geography, and Ethnic Studies"
  - term: "Department of Communication Studies"
  - term: "Department of Criminal Justice"
  - term: "Department of Economics, Agriculture, and Social Sciences"
  - term: "Department of English"
  - term: "Department of History"
  - term: "Department of Philosophy and Modern Languages"
  - term: "Department of Sociology, Gerontology, and Gender Studies"
  - term: "Department of Advanced Studies in Education"
  - term: "Department of Kinesiology"
  - term: "Department of Liberal Studies"
  - term: "Department of Social Work"
  - term: "Department of Biological Sciences"
  - term: "Department of Chemistry"
  - term: "Department of Computer Science"
  - term: "Department of Mathematics"
  - term: "Department of Physics, Physical Sciences, and Geology"
  - term: "Department of Psychology and Child Development"
  - term: "School of Nursing"
  - term: "Department of Accounting and Finance"
  - term: "Department of Management Information Systems"
  - term: "Department of Management, Operations, and Marketing"
  - term: "Department of Political Science and Public Administration"
  - term: "Doctor of Education in Educational Leadership"
  - term: "Interdisciplinary Studies Program"
  - term: "Master of Business Administration"
  - term: "Other Academic Units"
