terms:
  - term: "Academic Policies & Planning Committee"
  - term: "Academic Resources"
  - term: "Academic Senate Meetings"
  - term: "Administrative Division"
  - term: "Administrative Operations and Organizational Excellence"
  - term: "Advancement"
  - term: "Advancement Services"
  - term: "Aerospace Studies"
  - term: "Africana Studies Program"
  - term: "Alumni Relations"
  - term: "Armenian Studies Program"
  - term: "Auxiliary Operations & Enterprise Development"
  - term: "Business Teacher Education"
  - term: "Community & Economic Development (OCED)"
  - term: "Construction Management Program"
  - term: "Continuing & Global Education"
  - term: "Department of Accountancy"
  - term: "Department of Agricultural Business"
  - term: "Department of Animal Sciences and Agricultural Education"
  - term: "Department of Anthropology"
  - term: "Department of Art and Design"
  - term: "Department of Biology"
  - term: "Department of Chemistry"
  - term: "Department of Chicano and Latin American Studies"
  - term: "Department of Civil and Geomatics Engineering"
  - term: "Department of Communication"
  - term: "Department of Communicative Disorders and Deaf Studies"
  - term: "Department of Computer Science"
  - term: "Department of Counselor Education and Rehabilitation"
  - term: "Department of Criminology"
  - term: "Department of Curriculum and Instruction"
  - term: "Department of Earth and Environmental Sciences"
  - term: "Department of Economics"
  - term: "Department of Educational Leadership"
  - term: "Department of Electrical and Computer Engineering"
  - term: "Department of English"
  - term: "Department of Finance and Business Law"
  - term: "Department of Food Science and Nutrition"
  - term: "Department of Geography and City & Regional Planning"
  - term: "Department of History"
  - term: "Department of Industrial Technology"
  - term: "Department of Information Systems and Decision Sciences"
  - term: "Department of Kinesiology"
  - term: "Department of Linguistics"
  - term: "Department of Literacy, Early, Bilingual, and Special Education"
  - term: "Department of Management"
  - term: "Department of Marketing and Logistics"
  - term: "Department of Mass Communication and Journalism"
  - term: "Department of Mechanical Engineering"
  - term: "Department of Military Science (Army ROTC)"
  - term: "Department of Modern and Classical Languages and Literatures"
  - term: "Department of Music"
  - term: "Department of Philosophy"
  - term: "Department of Physical Therapy"
  - term: "Department of Physics"
  - term: "Department of Plant Science"
  - term: "Department of Political Science"
  - term: "Department of Psychology"
  - term: "Department of Public Health"
  - term: "Department of Recreation Administration"
  - term: "Department of Social Work Education"
  - term: "Department of Sociology"
  - term: "Department of Theatre Arts"
  - term: "Department of Viticulture and Enology"
  - term: "Development"
  - term: "Digital Services Division"
  - term: "DISCOVERe Hub"
  - term: "Doctoral Program in Educational Leadership"
  - term: "Enrollment Management"
  - term: "Executive Committee"
  - term: "FACEL"
  - term: "Facilities Management"
  - term: "Faculty Affairs"
  - term: "Faculty Equity & Diversity"
  - term: "General Education Committee"
  - term: "Graduate Committee"
  - term: "Graduate Studies"
  - term: "Human Resources"
  - term: "Institutional Effectiveness"
  - term: "Intellectual Property Review Committee"
  - term: "International Student Support Programs"
  - term: "Lyles Center for Innovation & Enterpreneurship"
  - term: "Maddy Institute"
  - term: "Nominating / Elections Committee"
  - term: "Personnel Committee"
  - term: "Public Safety/University Police Department"
  - term: "Public Services Division"
  - term: "Research & Sponsored Programs"
  - term: "Research Awards Review Committee"
  - term: "Richter Center For Community Engagement & Service-Learning"
  - term: "School of Nursing"
  - term: "Special Collections Research Centers Division"
  - term: "Student Affairs"
  - term: "Student Affairs Administration"
  - term: "Student Success Services"
  - term: "Student Health and Wellness Services"
  - term: "Technology Innovations For Learning And Teaching And Center For The Scholarly Advancement Of Learning And Teaching (TILT/CSALT)"
  - term: "Undergraduate Studies"
  - term: "University Communications"
  - term: "University Initiatives"
  - term: "Vice Provost"
  - term: "Women's Studies Program"
