terms:
  - term: "Aerospace Engineering"
  - term: "Agricultural Science"
  - term: "Animal Science"
  - term: "Biological Sciences"
  - term: "Business Administration"
  - term: "Chemistry & Biochemistry"
  - term: "Civil Engineering"
  - term: "Computer Science"
  - term: "Economics"
  - term: "Education"
  - term: "Electrical & Computer Engineering"
  - term: "Engineering Management"
  - term: "Geological Sciences"
  - term: "History"
  - term: "Kinesiology"
  - term: "Landscape Architecture"
  - term: "Mathematics & Statistics"
  - term: "Mechanical Engineering"
  - term: "Nutrition & Food Sciences"
  - term: "Plant Science"
  - term: "Political Science"
  - term: "Public Administration"
  - term: "Systems Engineering"
  - term: "Urban & Regional Planning"
  - term: "Collins College of Hospitality Management"
  - term: "John T. Lyle Center for Regenerative Studies"
