terms:
  - term: "Art"
  - term: "Cinema and Television Arts"
  - term: "Communication Studies"
  - term: "Journalism"
  - term: "Music"
  - term: "Theatre"
  - term: "Accounting and Information Systems"
  - term: "Business Law"
  - term: "Economics"
  - term: "Finance, Real Estate and Insurance"
  - term: "Management"
  - term: "Marketing"
  - term: "Systems and Operations Management"
  - term: "Deaf Studies"
  - term: "Educational Leadership and Policy Studies"
  - term: "Educational Psychology and Counseling"
  - term: "Elementary Education"
  - term: "Secondary Education"
  - term: "Special Education"
  - term: "Civil Engineering and Construction Management Technology"
  - term: "Computer Science"
  - term: "Electrical and Computer Engineering"
  - term: "Manufacturing System Engineering and Management"
  - term: "Mechanical Engineering"
  - term: "Child and Adolescent Development"
  - term: "Communication Disorders and Sciences"
  - term: "Environmental and Occupational Health"
  - term: "Family and Consumer Sciences"
  - term: "Health Sciences"
  - term: "Kinesiology"
  - term: "Nursing"
  - term: "Physical Therapy"
  - term: "Recreation and Tourism Management"
  - term: "Asian American Studies"
  - term: "Chicana/o Studies"
  - term: "English"
  - term: "Gender and Women Studies"
  - term: "Linguistics"
  - term: "Modern and Classical Languages and Literatures"
  - term: "Philosophy"
  - term: "Religious Studies"
  - term: "Biology"
  - term: "Chemistry and Biochemistry"
  - term: "Geological Sciences"
  - term: "Mathematics"
  - term: "Physics and Astronomy"
  - term: "Africana Studies"
  - term: "Anthropology"
  - term: "Criminology and Justice Studies"
  - term: "Geography and Environmental Studies"
  - term: "History"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Social Work"
  - term: "Sociology"
  - term: "Urban Studies and Planning"
