terms:
  - term: "Academic Affairs"
  - term: "Administration and Finance"
  - term: "Advising and Student Success Center"
  - term: "Brand Values Research Center"
  - term: "California Desert Studies Consortium"
  - term: "Catalyst Center"
  - term: "Center for Applied Biotechnology Studies (CABS)"
  - term: "Center for Autism: Applied Developmental Core"
  - term: "Center for Autism"
  - term: "Center for Boys and Men"
  - term: "Center for Cancer Disparities Research"
  - term: "Center for Careers in Teaching"
  - term: "Center for Children Who Stutter"
  - term: "Center for Collaborative Research and Prototype Development (CCRPD)"
  - term: "Center for Community Collaboration"
  - term: "Center for Computational and Applied Mathematics (CCAM)"
  - term: "Center for Corporate Reporting and Governance"
  - term: "Center for Demographic Research (CDR)"
  - term: "Center for Economic Education"
  - term: "Center for Entertainment and Hospitality Management"
  - term: "Center for Entertainment and Tourism Communications"
  - term: "Center for Entrepreneurship"
  - term: "Center for Family Business"
  - term: "Center for Healthy Neighborhoods"
  - term: "Center for Information Technology and Business Analytics"
  - term: "Center for Insurance Studies"
  - term: "Center for Leadership"
  - term: "Center for Maximizing Teacher Impact (CMTI)"
  - term: "Center for Nursing Workforce Excellence"
  - term: "Center for Oral and Public History (COPH)"
  - term: "Center for Public Policy (CPP)"
  - term: "Center for Research on Educational Access and Leadership (C-REAL)"
  - term: "Center for Sociocultural Sport and Olympic Research"
  - term: "Center for Sport Performance"
  - term: "Center for Successful Aging"
  - term: "Center for Sustainability"
  - term: "Center for the Promotion of Healthy Lifestyles and Obesity Prevention"
  - term: "Daily Titan (Student Newspaper)"
  - term: "Department of Accounting"
  - term: "Department of African American Studies"
  - term: "Department of Aging Studies"
  - term: "Department of American Studies"
  - term: "Department of Anthropology"
  - term: "Department of Asian American Studies"
  - term: "Department of Biological Sciences"
  - term: "Department of Chemistry and Biochemistry"
  - term: "Department of Chicana and Chicano Studies"
  - term: "Department of Child and Adolescent Studies"
  - term: "Department of Cinema and Television Arts"
  - term: "Department of Civil and Environmental Engineering"
  - term: "Department of Communication Sciences and Disorders"
  - term: "Department of Communications"
  - term: "Department of Computer Science"
  - term: "Department of Counseling"
  - term: "Department of Economics"
  - term: "Department of Educational Leadership"
  - term: "Department of Electrical Engineering"
  - term: "Department of Elementary and Bilingual Education"
  - term: "Department of English, Comparative Literature, and Linguistics"
  - term: "Department of Environmental Studies"
  - term: "Department of European Studies"
  - term: "Department of Finance"
  - term: "Department of Geography and the Environment"
  - term: "Department of Geological Sciences"
  - term: "Department of History"
  - term: "Department of Human Communication Studies"
  - term: "Department of Human Services"
  - term: "Department of Information Systems & Decision Sciences"
  - term: "Department of Kinesiology"
  - term: "Department of Latin American Studies"
  - term: "Department of Liberal Studies"
  - term: "Department of Literacy Reading Education"
  - term: "Department of Management"
  - term: "Department of Marketing / Business Communications"
  - term: "Department of Mathematics"
  - term: "Department of Mechanical Engineering"
  - term: "Department of Modern Languages and Literatures"
  - term: "Department of Philosophy"
  - term: "Department of Physics"
  - term: "Department of Politics, Administration, and Justice"
  - term: "Department of Psychology"
  - term: "Department of Public Health"
  - term: "Department of Religious Studies"
  - term: "Department of Secondary Education"
  - term: "Department of Social Work"
  - term: "Department of Sociology"
  - term: "Department of Special Education"
  - term: "Department of Theatre and Dance"
  - term: "Department of Visual Arts"
  - term: "Department of Women and Gender Studies"
  - term: "ECS Center for Cybersecurity"
  - term: "Fibromyalgia and Chronic Pain Center"
  - term: "Fullerton International Resources for Students and Teachers (FIRST)"
  - term: "Gianneschi Center for Nonprofit Research"
  - term: "Grand Central Art Center"
  - term: "Gravitational Wave Physics and Astronomy Center (GWPAC)"
  - term: "Hazel Miller Croy Reading Center"
  - term: "Health Promotion Research Institute"
  - term: "Human Resources, Diversity and Inclusion"
  - term: "Information Technology"
  - term: "Maxwell Center for International Communications"
  - term: "Nicholas and Lee Begovich Gallery"
  - term: "Office of the President"
  - term: "Pollak Library"
  - term: "Real Estate and Land Use Institute"
  - term: "School of Music"
  - term: "School of Nursing"
  - term: "Schools First Federal Credit Union Center for Creativity and Critical Thinking"
  - term: "Small Business Development Center"
  - term: "Small Business Institute"
  - term: "Social Science Research Center"
  - term: "South Central Cosatal Information Center"
  - term: "Student Affairs"
  - term: "The Sales Leadership Center"
  - term: "University Advancement"
  - term: "Woods Center for Economic Analysis and Forecasting"
