terms:
  - term: Accounting
  - term: Aerospace Engineering
  - term: Agribusiness & Food Industry Management/Agricultural Science
  - term: Animal & Veterinary Sciences
  - term: Architecture
  - term: Art
  - term: Biological Sciences
  - term: Chemicals & Materials Engineering
  - term: Chemistry and Biochemistry
  - term: Childhood Studies
  - term: Civil Engineering
  - term: Collins College of Hospitality Management
  - term: Communication
  - term: Computer Information Systems
  - term: Computer Science
  - term: Education
  - term: Electrical & Computer Engineering
  - term: Electromechanical Engineering Technology
  - term: English & Modern Languages
  - term: Ethnic and Women's Studies
  - term: Economics
  - term: Finance, Real Estate, & Law
  - term: Geography & Anthropology
  - term: Geological Sciences
  - term: History
  - term: Industrial & Manufacturing Engineering
  - term: Interdisciplinary General Education
  - term: International Business & Marketing
  - term: John T. Lyle Center for Regenerative Studies
  - term: Kinesiology & Health Promotion
  - term: Landscape Architecture
  - term: Leadership
  - term: Liberal Studies
  - term: Management & Human Resources
  - term: Mathematics & Statistics
  - term: Mechanical Engineering
  - term: Merchandising & Management
  - term: Music
  - term: Nutrition & Food Science
  - term: Philosophy
  - term: Physics & Astronomy
  - term: Plant Science
  - term: Political Science
  - term: Psychology
  - term: Sociology
  - term: Technology & Operations Management
  - term: Theater & New Dance
  - term: Urban & Regional Planning
