terms:
  - term: "Anthropology"
  - term: "English"
  - term: "Social Science"
  - term: "Sociology"
  - term: "Theatre Arts"
  - term: "Biology"
  - term: "Environmental Resources Engineering"
  - term: "Environmental Systems"
  - term: "Fisheries"
  - term: "Forestry"
  - term: "Geology"
  - term: "Mathematical models"
  - term: "Natural Resources"
  - term: "Wildlife"
  - term: "Business"
  - term: "Education"
  - term: "Kinesiology"
  - term: "Psychology"
  - term: "Social Work"
