terms:
  - term: "Accounting"
  - term: "American Indian Studies"
  - term: "Anthropology"
  - term: "Biological Sciences"
  - term: "Business Administration"
  - term: "Chemistry & Biochemistry"
  - term: "Communication"
  - term: "Computer Science & Information Systems"
  - term: "Economics"
  - term: "Education"
  - term: "Engineering"
  - term: "Environmental Studies"
  - term: "Ethnic Studies"
  - term: "Film Studies"
  - term: "Finance"
  - term: "Global Business Management"
  - term: "Global Studies"
  - term: "History"
  - term: "Human Development"
  - term: "Kinesiology"
  - term: "Liberal Studies"
  - term: "Literature and Writing Studies"
  - term: "Management"
  - term: "Management information systems"
  - term: "Marketing"
  - term: "Mathematics"
  - term: "Modern Language Studies"
  - term: "Nursing"
  - term: "Operations & Supply Chain Management"
  - term: "Philosophy"
  - term: "Physics"
  - term: "Political Science"
  - term: "Psychology"
  - term: "School of Arts -- Art, Media, and Design"
  - term: "School of Arts -- Music"
  - term: "School of Arts -- Theatre Arts"
  - term: "School of Arts -- Dance Studies"
  - term: "Social Sciences"
  - term: "Social Work"
  - term: "Sociology"
  - term: "Speech-Language Pathology"
  - term: "Women's, Gender, and Sexuality Studies"
