# taken from https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf
terms:
  - id: Audiovisual
    term: Audiovisual
  - id: Collection
    term: Collection
  - id: Data Paper
    term: Data Paper
  - id: Dataset
    term: Dataset
  - id: Event
    term: Event
  - id: Image
    term: Image
  - id: Interactive Resource
    term: Interactive Resource
  - id: Model
    term: Model
  - id: Physical Object
    term: Physical Object
  - id: Service
    term: Service
  - id: Software
    term: Software
  - id: Sound
    term: Sound
  - id: Text
    term: Text
