
campus: 'Fresno'
work_type: "default"
metadata_file: "mets.xml"
# metadata_prefix: "//xmlns:mdWrap[@OTHERMDTYPE='DIM']/dim:xmldata/dim:dim[@dspaceType='ITEM']"
# item_metadata_prefix: "//dim:dim[@dspaceType='ITEM']"
# collection_metadata_prefix: "//dim:dim[@dspaceType='COLLECTION']"
depositor: kcloud@calstate.edu
input_dir: /data/exported/
admin_set_id: 'v118rd525'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: true

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: California State University, Fresno

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Thesis: Thesis
  Dissertation: Thesis
  Project: Thesis
  Graduate Project: Thesis
  Student Research: Thesis
  Newspaper: Publication
  Journal Issue: Publication
  Poster: Publication
  Report: Publication
  Preprint: Publication
  Technical Report: Publication
  Working Paper: Publication
  Learning Object: EducationalResource
  Text: Publication
  Dataset: Dataset
  Abstracts: Thesis
  Agendas: Thesis
  Animations: Thesis
  Articles: Publication
  Biographical Items: Publication
  Blogs: Publication
  Post-print: Publication
  Pre-print: Publication
  Book chapters: Publication
  Book entry: Publication
  Books: Publication
  #Budgets
  #Catalogs
  #Correction
  Conference materials: Publication
  Conference Papers: Publication
  Conference papers: Publication
  Conference proceedings: Publication
  Dissertations: Thesis
  Doctoral Projects: Thesis
  Documents: Publication
  Editorial Materials: Publication
  Essays: Publication
  #Flyers
  #Image
  Presentations: Publication
  Journals: Publication
  Letters: Publication
  Interviews: Publication
  Notes: Publication
  Other: EducationalResource
  Magazines: Publication
  Memorandums: Publication
  Minutes: Publication
  News release: Publication
  Newsletters: Publication
  Newspapers: Publication
  Panels: Publication
  Plans/Blueprints: Publication
  Proceedings: Publication
  Speeches: Publication
  #Poems:
  #Poetry
  Policies: Publication
  Reviews: Publication
  Posters: Publication
  Presentations: Publication
  Press releases: Publication
  Proposals: Publication
  Reports: Publication
  Resolutions: Publication
  Slides: Publication
  Speeches: Publication
  #Sports
  #Text
  Theses: Thesis
  Transcripts: Publication
  Translations: Publication
  Webinars: EducationalResource

DSpace COMMUNITY:
  desc_metadata_prefix: "//dim:dim[@dspaceType='COMMUNITY']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

DSpace COLLECTION:
  desc_metadata_prefix: "//dim:dim[@dspaceType='COLLECTION']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

DSpace ITEM:
  desc_metadata_prefix: "//xmlns:mdWrap[@OTHERMDTYPE='DIM']/xmlns:xmlData/dim:dim[@dspaceType='ITEM']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

# Dublin Core Field Mapping
fields:
  description: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='illustration']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='reference']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='tableofcontents']"
    type: Array
  advisor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='advisor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
    type: Array
  alternative_title: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][@qualifier='alternative']"
    type: Array
  bibliographic_citation:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
    type: Array
  committee_member: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeemember']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeeMember']"
    type: Array
  contributor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='Interviewee']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='Interviewer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='Narrator']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='illustrator']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='local']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='photographer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='player']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='presenter']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='reviewer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='speaker']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='translator']"
    type: Array
  creator:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='author']"
      - "/dim:field[@mdschema='dc'][@element='creator'][not(@qualifier)]"
    type: Array
  date_accessioned:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
    type: String
  date_created:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
    type: Array
  date_copyright:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='copyright']"
    type: String
  date_issued:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='issued']"
    type: Array
  date_modified:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
    type: String
  date_published:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='published']"
    type: String
  date_submitted: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='submitted']"
    type: Array
  date_uploaded:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
    type: String
  degree_name:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='degree'][not(@qualifier)]"
    type: Array
  department:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='department']"
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='sponsor']"
    type: Array
  editor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='editor']"
    type: Array
  embargo_release_date:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
    type: String
  embargo_terms:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
    type: String
  extent:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='medium']"
      - "/dim:field[@mdschema='dc'][@element='format'][not(@qualifier)]"
    type: Array
  geographical_area:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
    type: Array
  handle:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
    type: Array
  identifier:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='coursenumber']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
    type: Array
  is_part_of:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
    type: Array
  keyword:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
    type: Array
  language:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='language'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='language'][@qualifier='iso']"
    type: Array
  license:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='license']"
    type: Array
  provenance:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
      - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
    type: Array
  publisher:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='issuer'][not(@qualifier)]"
    type: Array
  related_url:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
    type: Array
  resource_type:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='type'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='type'][@qualifier='genre']"
      - "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  rights_statement:
    xpath:
#      - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
#      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='usage']"
    type: Array
  rights_holder:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='holder']"
  rights_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='statementofresponsibility']"
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='notice']"
    type: Array
  rights_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='uri']"
    type: Array
  sponsor: # Newspaper
    xpath:
      - "/dim:field[@mdschema='dc'][@element='sponsor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='sponsor']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='sponsorship']"
    type: Array
  subject:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='category']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='classification']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='other']"
    type: Array
  time_period: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='event']"
    type: Array
  title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][not(@qualifier)]"
    type: Array
