
campus: 'Humboldt'
work_type: "default"
metadata_file: "mets.xml"
depositor: kcloud@calstate.edu
input_dir: /data/exported/
handle_report: /data/tmp/MAIN_handle_report.txt
admin_set_id: 9880vq965

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: false

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: Humboldt State University

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Abstract: Thesis
  Article: Publication
  Audio: Publication
  Bibliography: Publication
  Book: Publication
  Book chapter: Publication
  Book review: Publication
  Conference materials: Publication
  Dissertation: Thesis
  dissertation: Thesis
  Graduate Project: Thesis
  Image: Publication
  Learning Object: Thesis
  Map: Publication
  Masters thesis: Thesis
  Newsletter: Publication
  Poster: Publication
  Presentation: Publication
  Project: Thesis
  Recording, oral: Publication
  Recording, musical: Publication
  Report: Publication
  Schedule: Publication
  Student Research: Thesis
  sound: Publication
  Sound recording: Publication
  Table: Publication
  Technical Report: Publication
  Text: Publication
  Thesis: Thesis
  Masters Thesis: Thesis
  Working Paper: Publication
  Video: Publication

DSpace COMMUNITY:
  desc_metadata_prefix: "//dim:dim[@dspaceType='COMMUNITY']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

DSpace COLLECTION:
  desc_metadata_prefix: "//dim:dim[@dspaceType='COLLECTION']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

DSpace ITEM:
  desc_metadata_prefix: "//xmlns:mdWrap[@OTHERMDTYPE='DIM']/xmlns:xmlData/dim:dim[@dspaceType='ITEM']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

# Dublin Core Field Mapping
fields:
  description:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
    type: Array
  advisor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='advisor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
    type: Array
  alternative_title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][@qualifier='alternative']"
    type: Array
  bibliographic_citation:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
    type: Array
  committee_member:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeemember']"
    type: Array
  contributor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='editor']"
    type: Array
  creator:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='author']"
      - "/dim:field[@mdschema='dc'][@element='creator'][not(@qualifier)]"
    type: Array
  date_accessioned:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
    type: String
  date_created:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
    type: Array
  date_issued:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='issued']"
    type: Array
  date_modified:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
    type: String
  date_submitted: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='submitted']"
    type: Array
  date_uploaded:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
    type: String
  degree_name:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='degree']"
    type: Array
  department:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='program'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='department']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='program']"
    type: Array
  description_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='mimetype']"
    type: Array
  doi:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
    type: Array
  editor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='editor']"
    type: Array
  embargo_release_date:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
    type: String
  embargo_terms:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
    type: String
  extent:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
    type: Array
  geographical_area:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
    type: Array
  handle:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
    type: Array
  identifier:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
    type: Array
  is_part_of:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
    type: Array
  issn:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
    type: Array
  isbn:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
    type: Array
  keyword:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
    type: Array
  language:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='language'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='language'][@qualifier='iso']"
    type: Array
  provenance:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
      - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
    type: Array
  publisher:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
    type: Array
  related_url:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
      - "/dim:field[@mdschema='dc'][@element='relation'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='uri']"
    type: Array
  resource_type:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='type'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='type'][@qualifier='genre']"
      - "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  rights_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
    type: Array
  rights_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='uri']"
    type: Array
  sponsor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='sponsor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='sponsor']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='sponsorship']"
    type: Array
  subject:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='other']"
    type: Array
  time_period:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
    type: Array
  title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][not(@qualifier)]"
    type: Array
