
campus: 'Long Beach'
work_type: "default"
metadata_file: "rdf.xml"
depositor: kcloud@calstate.edu
input_dir: /data/csulb/exported/
admin_set_id: 'rj4304528'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: true

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: California State University, Long Beach

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  NULL: Thesis # University Honors Program
  NULL: CreativeWork # OLLI Memoir
  NULL: CreativeWork # Images from Art Collection
  NULL: Newspaper # Jewish Community Chronicle
  Interview: CreativeWork # VOAHA II: Virtual Oral/Aural History Archive
  Oral History: CreativeWork # VOAHA II: Virtual Oral/Aural History Archive
  Data tables: Dataset #7th St
  Geographic Information System spatial data: Dataset #7th St
  Text: Dataset #7th St
  #Dissertation: Thesis
  #Project: Thesis
  #Graduate Project: Thesis
  #Student Research: Thesis
  #Newspaper: Newspaper
  #Journal Issue: Publication
  #Article: Publication
  #Poster: Publication
  #Report: Publication
  #Preprint: Publication
  #Technical Report: Publication
  #Working Paper: Publication
  #painting: CreativeWork
  #ephemera: CreativeWork
  #textiles: CreativeWork
  #Empirical Research: CreativeWork
  #Award Materials: CreativeWork
  #photograph: CreativeWork
  #Mixed Media: CreativeWork
  #Other: CreativeWork
  #Creative Works: CreativeWork
  #Image: CreativeWork
  # Learning Object: Thesis
  # Post-print: Publication
  # Presentation: Thesis
  # Recording, oral: CreativeWork

# Dublin Core Field Mapping
fields:
  #description: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
  #  type: Array
  #advisor:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='advisor'][not(@qualifier)]"
  #    - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
  #  type: Array
  #alternative_title: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='title'][@qualifier='alternative']"
  #  type: Array
  #bibliographic_citation:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
  #  type: Array
  #committee_member: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeemember']"
  #  type: Array
  #contributor:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
  #  type: Array
  creator:
    xpath:
      - "/dc:creator"
    type: Array
  #date_accessioned:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
  #  type: String
  #date_created:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
  #    - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
  #  type: Array
  #date_issued:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='issued']"
  #  type: Array
  #date_modified:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
  #  type: String
  date_submitted: # Thesis
    xpath:
      - "/dc:date"
    type: Array
  #date_uploaded:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
  #  type: String
  description:
    xpath:
      - "/dc:description"
      - "/dcterms:tableOfContents"
    type: Array
  #embargo_release_date:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
  #  type: String
  #embargo_terms:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
  #  type: String
  #extent: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
  #  type: Array
  #geographical_area: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
  #  type: Array
  #handle: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
  #  type: Array
  identifier: #Art Collection
    xpath:
      - "/dc:identifier"
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
  #    - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
    type: Array
  #is_part_of: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
  #  type: Array
  keyword: # OLLI Memoirs
    xpath:
      - "/dc:subject"
    type: Array
  #language:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='language'][not(@qualifier)]"
  #    - "/dim:field[@mdschema='dc'][@element='language'][@qualifier='iso']"
  #  type: Array
  #license: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='license']"
  #  type: Array
  #provenance:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
  #    - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
  #  type: Array
  #publisher:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
  #  type: Array
  #related_url: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
  #  type: Array
  resource_type:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='type'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='type'][@qualifier='genre']"
      - "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  #rights_statement:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
  #    - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='usage']"
  #  type: Array
  sponsor: # 7th St Atlas
    xpath:
      - "/dc:relation"
    type: Array
  subject: # University Honors Program
    xpath:
      - "/dc:subject"
    type: Array
  #time_period: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
  #  type: Array
  title:
    xpath:
      - "/dc:title"
    type: Array
