
campus: 'Moss Landing'
subpathwork_type: "default"
#metadata_file: "MODS Record.xml"
metadata_file: "DC Record.xml"
# metadata_prefix: "//xmlns:mdWrap[@OTHERMDTYPE='DIM']/dim:xmldata/dim:dim[@dspaceType='ITEM']"
# item_metadata_prefix: "//dim:dim[@dspaceType='ITEM']"
# collection_metadata_prefix: "//dim:dim[@dspaceType='COLLECTION']"
depositor: kcloud@calstate.edu
input_dir: /data/mlml/exported
admin_set_id: '3t945q76s'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: true

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: Moss Landing Marine Laboratories

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Thesis: Thesis
  Dissertation: Thesis
  Project: Thesis
  Graduate Project: Thesis
  Student Research: Thesis
  Newspaper: Publication
  Journal Issue: Publication
  Article: Publication
  Poster: Publication
  Report: Publication
  Preprint: Publication
  Technical Report: Publication
  Working Paper: Publication
  painting: CreativeWork
  ephemera: CreativeWork
  textiles: CreativeWork
  Empirical Research: CreativeWork
  Award Materials: CreativeWork
  photograph: CreativeWork
  Mixed Media: CreativeWork
  Other: CreativeWork
  Creative Works: CreativeWork
  Image: CreativeWork
  Text: Publication
  Publication: Publication
  Abstract: Publication
  Periodical: Publication
  Journal: Publication
  journal: Publication
  Text, newsletter: Publication
  TechPub: Publication
  Text, Text, Newsletter: Publication
  MovingImage: CreativeWork
  StillImage: CreativeWork
  Buildings: CreativeWork
  ~: CreativeWork
  # Learning Object: Thesis
  # Post-print: Publication
  # Presentation: Thesis
  # Recording, oral: CreativeWork

#DSpace COMMUNITY:
#  desc_metadata_prefix: "//dim:dim[@dspaceType='COMMUNITY']"
#  namespace:
#    xmlns: http://www.loc.gov/METS/
#    dim: http://www.dspace.org/xmlns/dspace/dim

#DSpace COLLECTION:
#  desc_metadata_prefix: "//dim:dim[@dspaceType='COLLECTION']"
#  namespace:
#    xmlns: http://purl.org/dc/elements/1.1/
#    dim: http://www.dspace.org/xmlns/dspace/dim

Islandora ITEM:
  desc_metadata_prefix: "//oai_dc:dc"
  namespace:
    xmlns: http://www.openarchives.org/OAI/2.0/oai_dc/
    #dim: http://www.dspace.org/xmlns/dspace/dim

#Islandora MODS_ITEM:
#  desc_metadata_prefix: "//mods"
#  namespace:
#    xmlns: http://www.loc.gov/mods/v3
    #dim: http://www.dspace.org/xmlns/dspace/dim

#Islandora MODS Field Mapping
#fields:
# MODS description
#description:
#  xpath:
#    - "/mods/note"
#  type: Array
# MODS Subject
#subject:
#  xpath:
#    - "/mods/subject/{topic,geographic}"
#  type: Array
#

# Dublin Core Field Mapping
fields:
  abstract: # Thesis
    xpath:
      - "/dc.description[@qualifier='abstract']"
    type: Array
  advisor:
    xpath:
      - "/dc:contributor[contains(.,'Thesis advisor')]"
    type: Array
  alternative_title: # Thesis
    xpath:
      - "/dc.title[@qualifier='alternative']"
    type: Array
  #bibliographic_citation:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
  #  type: Array
  committee_member: # Thesis
    xpath:
      - "/dc:contributor[contains(.,'Thesis committee member')]"
    type: Array
  contributor:
    xpath:
      - "/dc:contributor[not(contains(.,'Thesis advisor'))][not(contains(.,'Thesis committee member'))]"
    type: Array
  #coverage:
  #  xpath:
  #    - "/dc:coverage"
  #  type: Array
  creator:
    xpath:
      - "/dc:creator"
      #- "/dim:field[@mdschema='dc'][@element='creator'][not(@qualifier)]"
    type: Array
  #date_accessioned:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
  #  type: String
  #date_created:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
  #    - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
  #  type: Array
  date_issued:
    xpath:
      - "/dc:date"
    type: Array
  #date_modified:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
  #  type: String
  #date_submitted: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='submitted']"
  #  type: Array
  #date_uploaded:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
  #  type: String
  description:
    xpath:
      - "/dc:description"
    type: Array
  #embargo_release_date:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
  #  type: String
  #embargo_terms:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
  #  type: String
  #extent: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
    type: Array
  #format: # (Default) Thesis
  #  xpath:
  #    - "/dc:format"
  #  type: Array
  #geographical_area: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
  #  type: Array
  #handle: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
  #  type: Array
  identifier:
    xpath:
      - "/dc:identifier"
    type: Array
  #is_part_of: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
  #  type: Array
  #keyword:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
  #  type: Array
  language:
    xpath:
      - "/dc:language"
    type: Array
  #license: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='license']"
  #  type: Array
  #provenance:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
  #    - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
  #  type: Array
  #publisher:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
  #  type: Array
  #related_url: # (Default) Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
  #  type: Array
  resource_type:
    xpath:
      - "/dc:type"
      #- "/dc:genre"
      #- "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  #rights_statement:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
  #    - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='usage']"
  #  type: Array
  #sponsor: # Newspaper
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='sponsor'][not(@qualifier)]"
  #    - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='sponsor']"
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='sponsorship']"
  #  type: Array
  subject:
    xpath:
      - "/dc:subject"
    type: Array
  #time_period: # Thesis
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
  #  type: Array
  title:
    xpath:
      - "/dc:title"
    type: Array
