
campus: 'Moss Landing'
subpathwork_type: "default"
metadata_file: "DC Record.xml"
data_file: "pdf"
depositor: kcloud@calstate.edu
input_dir: /data/exported/islandora/mosslanding
admin_set_id: '3t945q76s'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: true

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: Moss Landing Marine Laboratories

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Thesis: Thesis
  Dissertation: Thesis
  Project: Thesis
  Graduate Project: Thesis
  Student Research: Thesis
  Newspaper: Publication
  Journal Issue: Publication
  Article: Publication
  Poster: Publication
  Report: Publication
  Preprint: Publication
  Technical Report: Publication
  Working Paper: Publication
  painting: CreativeWork
  ephemera: CreativeWork
  textiles: CreativeWork
  Empirical Research: CreativeWork
  Award Materials: CreativeWork
  photograph: CreativeWork
  Mixed Media: CreativeWork
  Other: CreativeWork
  Creative Works: CreativeWork
  Image: CreativeWork
  Text: Publication
  Publication: Publication
  Abstract: Publication
  Periodical: Publication
  Journal: Publication
  journal: Publication
  Text, newsletter: Publication
  TechPub: Publication
  Text, Text, Newsletter: Publication
  MovingImage: CreativeWork
  StillImage: CreativeWork
  Buildings: CreativeWork
  ~: CreativeWork
  # Learning Object: Thesis
  # Post-print: Publication
  # Presentation: Thesis
  # Recording, oral: CreativeWork

Islandora ITEM:
  desc_metadata_prefix: "//oai_dc:dc"
  namespace:
    xmlns: http://www.openarchives.org/OAI/2.0/oai_dc/

# Dublin Core Field Mapping
fields:
  abstract:
    xpath:
      - "/dc.description[@qualifier='abstract']"
    type: Array
  advisor:
    xpath:
      - "/dc:contributor[contains(.,'Thesis advisor')]"
    type: Array
  alternative_title:
    xpath:
      - "/dc.title[@qualifier='alternative']"
    type: Array
  committee_member:
    xpath:
      - "/dc:contributor[contains(.,'Thesis committee member')]"
    type: Array
  contributor:
    xpath:
      - "/dc:contributor[not(contains(.,'Thesis advisor'))][not(contains(.,'Thesis committee member'))]"
    type: Array
  creator:
    xpath:
      - "/dc:creator"
    type: Array
  date_issued:
    xpath:
      - "/dc:date"
    type: Array
  description:
    xpath:
      - "/dc:description"
    type: Array
  identifier:
    xpath:
      - "/dc:identifier"
    type: Array
  language:
    xpath:
      - "/dc:language"
    type: Array
  resource_type:
    xpath:
      - "/dc:type"
      #- "/dc:genre"
      #- "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  subject:
    xpath:
      - "/dc:subject"
    type: Array
  title:
    xpath:
      - "/dc:title"
    type: Array
