development:
  host: <%= ENV.fetch('REDIS_SERVER', 'localhost') %>
  port: 6379
test:
  host: <%= ENV.fetch('REDIS_SERVER', 'localhost') %>
  port: 6379
production:
  host: <%= ENV['REDIS_SERVER'] %>
  port: <%= ENV['REDIS_PORT'] %>
